sudo: required
language: generic


services:
  - docker

before_install:
  - docker build -t brucejmcclure/Travis -f Docerfile.dev .


  script:
    - docker run -e CI=true brucejmcclure/Travis-react npm run test